# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\ericWorkspace\5G console\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 492)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_6_tab1 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_6_tab1.setObjectName("gridLayout_6_tab1")
        self.groupBox_4_tab1 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_4_tab1.setObjectName("groupBox_4_tab1")
        self.gridLayout_4_tab1 = QtWidgets.QGridLayout(self.groupBox_4_tab1)
        self.gridLayout_4_tab1.setObjectName("gridLayout_4_tab1")
        self.plainTextEdit_4_tab1 = QtWidgets.QPlainTextEdit(self.groupBox_4_tab1)
        self.plainTextEdit_4_tab1.setObjectName("plainTextEdit_4_tab1")
        self.gridLayout_4_tab1.addWidget(self.plainTextEdit_4_tab1, 0, 0, 1, 1)
        self.gridLayout_6_tab1.addWidget(self.groupBox_4_tab1, 1, 0, 1, 2)
        self.groupBox_5_tab1 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_5_tab1.setObjectName("groupBox_5_tab1")
        self.gridLayout_5_tab1 = QtWidgets.QGridLayout(self.groupBox_5_tab1)
        self.gridLayout_5_tab1.setObjectName("gridLayout_5_tab1")
        self.plainTextEdit_5_tab1 = QtWidgets.QPlainTextEdit(self.groupBox_5_tab1)
        self.plainTextEdit_5_tab1.setObjectName("plainTextEdit_5_tab1")
        self.gridLayout_5_tab1.addWidget(self.plainTextEdit_5_tab1, 0, 0, 1, 1)
        self.gridLayout_6_tab1.addWidget(self.groupBox_5_tab1, 1, 2, 1, 1)
        self.groupBox_3_tab1 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_3_tab1.setObjectName("groupBox_3_tab1")
        self.gridLayout_3_tab1 = QtWidgets.QGridLayout(self.groupBox_3_tab1)
        self.gridLayout_3_tab1.setObjectName("gridLayout_3_tab1")
        self.plainTextEdit_3_tab1 = QtWidgets.QPlainTextEdit(self.groupBox_3_tab1)
        self.plainTextEdit_3_tab1.setObjectName("plainTextEdit_3_tab1")
        self.gridLayout_3_tab1.addWidget(self.plainTextEdit_3_tab1, 0, 0, 1, 1)
        self.gridLayout_6_tab1.addWidget(self.groupBox_3_tab1, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab1, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 701, 23))
        self.menuBar.setObjectName("menuBar")
        self.menulink_settings = QtWidgets.QMenu(self.menuBar)
        self.menulink_settings.setObjectName("menulink_settings")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.cellcfgs = QtWidgets.QMenu(self.menuBar)
        self.cellcfgs.setObjectName("cellcfgs")
        self.commenquery = QtWidgets.QMenu(self.menuBar)
        self.commenquery.setObjectName("commenquery")
        MainWindow.setMenuBar(self.menuBar)
        self.actionlink = QtWidgets.QAction(MainWindow)
        self.actionlink.setObjectName("actionlink")
        self.actionnew_tab = QtWidgets.QAction(MainWindow)
        self.actionnew_tab.setObjectName("actionnew_tab")
        self.actionchongqi = QtWidgets.QAction(MainWindow)
        self.actionchongqi.setObjectName("actionchongqi")
        self.actionIMSI = QtWidgets.QAction(MainWindow)
        self.actionIMSI.setObjectName("actionIMSI")
        self.cellcfgf003 = QtWidgets.QAction(MainWindow)
        self.cellcfgf003.setObjectName("cellcfgf003")
        self.cellcfgquery = QtWidgets.QAction(MainWindow)
        self.cellcfgquery.setObjectName("cellcfgquery")
        self.cellstatequery = QtWidgets.QAction(MainWindow)
        self.cellstatequery.setObjectName("cellstatequery")
        self.pwrquery = QtWidgets.QAction(MainWindow)
        self.pwrquery.setObjectName("pwrquery")
        self.workmodef006 = QtWidgets.QAction(MainWindow)
        self.workmodef006.setObjectName("workmodef006")
        self.workmodequery = QtWidgets.QAction(MainWindow)
        self.workmodequery.setObjectName("workmodequery")
        self.actionaddcell = QtWidgets.QAction(MainWindow)
        self.actionaddcell.setObjectName("actionaddcell")
        self.menulink_settings.addAction(self.actionlink)
        self.menulink_settings.addAction(self.actionnew_tab)
        self.menulink_settings.addAction(self.actionIMSI)
        self.menu.addAction(self.actionchongqi)
        self.cellcfgs.addAction(self.actionaddcell)
        self.commenquery.addAction(self.cellcfgquery)
        self.commenquery.addAction(self.cellstatequery)
        self.commenquery.addAction(self.pwrquery)
        self.commenquery.addAction(self.workmodequery)
        self.menuBar.addAction(self.menulink_settings.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.cellcfgs.menuAction())
        self.menuBar.addAction(self.commenquery.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.tab2 = QtWidgets.QWidget()
        self.gridLayout_6_tab2=QtWidgets.QGridLayout(self.tab2)
        self.groupBox_3_tab2=QtWidgets.QGroupBox(self.tab2)
        self.gridLayout_3_tab2=QtWidgets.QGridLayout(self.groupBox_3_tab2)
        self.plainTextEdit_3_tab2=QtWidgets.QPlainTextEdit(self.groupBox_3_tab2)
        self.groupBox_5_tab2=QtWidgets.QGroupBox(self.tab2)
        self.gridLayout_5_tab2=QtWidgets.QGridLayout(self.groupBox_5_tab2)
        self.plainTextEdit_5_tab2=QtWidgets.QPlainTextEdit(self.groupBox_5_tab2)
        self.groupBox_4_tab2=QtWidgets.QGroupBox(self.tab2)
        self.gridLayout_4_tab2=QtWidgets.QGridLayout(self.groupBox_4_tab2)
        self.plainTextEdit_4_tab2=QtWidgets.QPlainTextEdit(self.groupBox_4_tab2)

        self.tab3 = QtWidgets.QWidget()
        self.gridLayout_6_tab3=QtWidgets.QGridLayout(self.tab3)
        self.groupBox_3_tab3=QtWidgets.QGroupBox(self.tab3)
        self.gridLayout_3_tab3=QtWidgets.QGridLayout(self.groupBox_3_tab3)
        self.plainTextEdit_3_tab3=QtWidgets.QPlainTextEdit(self.groupBox_3_tab3)
        self.groupBox_5_tab3=QtWidgets.QGroupBox(self.tab3)
        self.gridLayout_5_tab3=QtWidgets.QGridLayout(self.groupBox_5_tab3)
        self.plainTextEdit_5_tab3=QtWidgets.QPlainTextEdit(self.groupBox_5_tab3)
        self.groupBox_4_tab3=QtWidgets.QGroupBox(self.tab3)
        self.gridLayout_4_tab3=QtWidgets.QGridLayout(self.groupBox_4_tab3)
        self.plainTextEdit_4_tab3=QtWidgets.QPlainTextEdit(self.groupBox_4_tab3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4_tab1.setTitle(_translate("MainWindow", "操作日志"))
        self.groupBox_5_tab1.setTitle(_translate("MainWindow", "心跳"))
        self.groupBox_3_tab1.setTitle(_translate("MainWindow", "查询信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "新建连接"))
        self.menulink_settings.setTitle(_translate("MainWindow", "连接设置"))
        self.menu.setTitle(_translate("MainWindow", "板卡设置"))
        self.cellcfgs.setTitle(_translate("MainWindow", "小区参数配置"))
        self.commenquery.setTitle(_translate("MainWindow", "常用查询"))
        self.actionlink.setText(_translate("MainWindow", "连接"))
        self.actionnew_tab.setText(_translate("MainWindow", "新建连接"))
        self.actionchongqi.setText(_translate("MainWindow", "重启板卡"))
        self.actionIMSI.setText(_translate("MainWindow", "IMSI 列表"))
        self.cellcfgf003.setText(_translate("MainWindow", "小区参数配置F003"))
        self.cellcfgquery.setText(_translate("MainWindow", "小区参数查询F27"))
        self.cellstatequery.setText(_translate("MainWindow", "小区状态查询F02F"))
        self.pwrquery.setText(_translate("MainWindow", "衰减及增益查询F031"))
        self.workmodef006.setText(_translate("MainWindow", "工作模式配置F006"))
        self.workmodequery.setText(_translate("MainWindow", "工作模式查询F03D"))
        self.actionaddcell.setText(_translate("MainWindow", "小区配置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
